apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config
data:
  providerConfig: |
    application: reclassification-app
    baselineStartTime: "2021-11-03T11:29:46.915Z"
    canaryStartTime: "2021-11-03T11:29:46.915Z"
    lifetimeMinutes: 6
    intervalTime: 3
    lookBackType: sliding
    gitops: false
    passScore: 90
    serviceList:
    - logTemplateName: reclassificationtemp
      logScopeVariables: "kubernetes.container_name"
      baselineLogScope: "baseapp-rest-1"
      canaryLogScope: "canaryapp-rest-1"
