kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: tmpl-gitops
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: canary-score
      count: 1
      initialDelay: 10s    
      provider:
        opsmx:
          profile: opsmx-profile-new
          application: sanitytest1
          user: admin
          lifetimeMinutes: 3
          gitops: true
          threshold:
            pass: 60
            marginal: 40   
          services:
          - logTemplateName: logtemplate-01
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
           
